/* Simple config.h for gcc. */
#define HAVE_TYPEOF 1
#define HAVE_ALIGNOF 1
#define HAVE_STATEMENT_EXPR 1
#define HAVE_BUILTIN_EXPECT 1
#define HAVE_ATTRIBUTE_PRINTF 1
#define HAVE_BUILTIN_TYPES_COMPATIBLE_P 1
#define HAVE_BUILTIN_CHOOSE_EXPR 1
#define HAVE_LITTLE_ENDIAN 1
#define HAVE_BIG_ENDIAN 0
#define HAVE_MMAP 1
#define HAVE_GETPAGESIZE 1
#define HAVE_UTIME 1
