CFLAGS=-g -Wall -Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes -Wmissing-declarations -I../../.. ../../talloc.o ../../alloc.o ../../noerr.o ../../read_write_all.o ../../antithread.o # -O3
LDLIBS=-ljpeg -lm

all: dns_lookup arabella

clean:
	rm -f dns_lookup arabella
